from turtle import *
def city():
    #house 3
    up()
    home()
    down()
    speed(0)
    up()
    goto(-270, -380)
    down()
    color('maroon')
    begin_fill()
    fd(100)
    lt(90)
    fd(250)
    lt(90)
    fd(100)
    lt(90)
    fd(150)
    end_fill()
    lt(90)
    n = 0
    while n < 5:
        n += 1
        up()
        goto(-285 + 20*n, -375)
        down()
        color('white')
        begin_fill()
        for i in range(4):
            fd(10)
            lt(90)
        end_fill()

        up()
        goto(-285 + 20*n, -355)
        down()
        color('white')
        begin_fill()
        for i in range(4):
            fd(10)
            lt(90)
        end_fill()

        up()
        goto(-285 + 20*n, -335)
        down()
        color('white')
        begin_fill()
        for i in range(4):
            fd(10)
            lt(90)
        end_fill()

        up()
        goto(-285 + 20*n, -315)
        down()
        color('white')
        begin_fill()
        for i in range(4):
            fd(10)
            lt(90)
        end_fill()

        up()
        goto(-285 + 20*n, -295)
        down()
        color('white')
        begin_fill()
        for i in range(4):
            fd(10)
            lt(90)
        end_fill()

        up()
        goto(-285 + 20*n, -275)
        down()
        color('white')
        begin_fill()
        for i in range(4):
            fd(10)
            lt(90)
        end_fill()

        up()
        goto(-285 + 20*n, -255)
        down()
        color('white')
        begin_fill()
        for i in range(4):
            fd(10)
            lt(90)
        end_fill()

        up()
        goto(-285 + 20*n, -235)
        down()
        color('white')
        begin_fill()
        for i in range(4):
            fd(10)
            lt(90)
        end_fill()

        up()
        goto(-285 + 20*n, -215)
        down()
        color('white')
        begin_fill()
        for i in range(4):
            fd(10)
            lt(90)
        end_fill()

        up()
        goto(-285 + 20*n, -195)
        down()
        color('white')
        begin_fill()
        for i in range(4):
            fd(10)
            lt(90)
        end_fill()

        up()
        goto(-285 + 20*n, -175)
        down()
        color('white')
        begin_fill()
        for i in range(4):
            fd(10)
            lt(90)
        end_fill()

        up()
        goto(-285 + 20*n, -155)
        down()
        color('white')
        begin_fill()
        for i in range(4):
            fd(10)
            lt(90)
        end_fill()

    #house 3
    up()
    home()
    down()
    speed(0)
    up()
    goto(-130, -380)
    down()
    color('maroon')
    begin_fill()
    fd(100)
    lt(90)
    fd(250)
    lt(90)
    fd(100)
    lt(90)
    fd(150)
    end_fill()
    lt(90)
    n = 0
    while n < 5:
        n += 1
        up()
        goto(-145 + 20*n, -375)
        down()
        color('white')
        begin_fill()
        for i in range(4):
            fd(10)
            lt(90)
        end_fill()

        up()
        goto(-145 + 20*n, -355)
        down()
        color('white')
        begin_fill()
        for i in range(4):
            fd(10)
            lt(90)
        end_fill()

        up()
        goto(-145 + 20*n, -335)
        down()
        color('white')
        begin_fill()
        for i in range(4):
            fd(10)
            lt(90)
        end_fill()

        up()
        goto(-145 + 20*n, -315)
        down()
        color('white')
        begin_fill()
        for i in range(4):
            fd(10)
            lt(90)
        end_fill()

        up()
        goto(-145 + 20*n, -295)
        down()
        color('white')
        begin_fill()
        for i in range(4):
            fd(10)
            lt(90)
        end_fill()

        up()
        goto(-145 + 20*n, -275)
        down()
        color('white')
        begin_fill()
        for i in range(4):
            fd(10)
            lt(90)
        end_fill()

        up()
        goto(-145 + 20*n, -255)
        down()
        color('white')
        begin_fill()
        for i in range(4):
            fd(10)
            lt(90)
        end_fill()

        up()
        goto(-145 + 20*n, -235)
        down()
        color('white')
        begin_fill()
        for i in range(4):
            fd(10)
            lt(90)
        end_fill()

        up()
        goto(-145 + 20*n, -215)
        down()
        color('white')
        begin_fill()
        for i in range(4):
            fd(10)
            lt(90)
        end_fill()

        up()
        goto(-145 + 20*n, -195)
        down()
        color('white')
        begin_fill()
        for i in range(4):
            fd(10)
            lt(90)
        end_fill()

        up()
        goto(-145 + 20*n, -175)
        down()
        color('white')
        begin_fill()
        for i in range(4):
            fd(10)
            lt(90)
        end_fill()

        up()
        goto(-145 + 20*n, -155)
        down()
        color('white')
        begin_fill()
        for i in range(4):
            fd(10)
            lt(90)
        end_fill()

    #house 1
    up()
    home()
    down()
    speed(0)
    up()
    goto(-350, -380)
    down()
    color('black')
    begin_fill()
    fd(100)
    lt(90)
    fd(150)
    lt(90)
    fd(100)
    lt(90)
    fd(150)
    end_fill()
    lt(90)
    n = 0
    while n < 5:
        n += 1
        up()
        goto(-365 + 20*n, -375)
        down()
        color('white')
        begin_fill()
        for i in range(4):
            fd(10)
            lt(90)
        end_fill()

        up()
        goto(-365 + 20*n, -355)
        down()
        color('white')
        begin_fill()
        for i in range(4):
            fd(10)
            lt(90)
        end_fill()

        up()
        goto(-365 + 20*n, -335)
        down()
        color('white')
        begin_fill()
        for i in range(4):
            fd(10)
            lt(90)
        end_fill()

        up()
        goto(-365 + 20*n, -315)
        down()
        color('white')
        begin_fill()
        for i in range(4):
            fd(10)
            lt(90)
        end_fill()

        up()
        goto(-365 + 20*n, -295)
        down()
        color('white')
        begin_fill()
        for i in range(4):
            fd(10)
            lt(90)
        end_fill()

        up()
        goto(-365 + 20*n, -275)
        down()
        color('white')
        begin_fill()
        for i in range(4):
            fd(10)
            lt(90)
        end_fill()

        up()
        goto(-365 + 20*n, -255)
        down()
        color('white')
        begin_fill()
        for i in range(4):
            fd(10)
            lt(90)
        end_fill()

    #house 2
    up()
    home()
    down()
    speed(0)
    up()
    goto(-210, -380)
    down()
    color('dark gray')
    begin_fill()
    fd(100)
    lt(90)
    fd(350)
    lt(90)
    fd(100)
    lt(90)
    fd(350)
    end_fill()
    lt(90)
    n = 0
    while n < 5:
        n += 1
        up()
        goto(-225 + 20*n, -375)
        down()
        color('white')
        begin_fill()
        for i in range(4):
            fd(10)
            lt(90)
        end_fill()

        up()
        goto(-225 + 20*n, -355)
        down()
        color('white')
        begin_fill()
        for i in range(4):
            fd(10)
            lt(90)
        end_fill()

        up()
        goto(-225 + 20*n, -335)
        down()
        color('white')
        begin_fill()
        for i in range(4):
            fd(10)
            lt(90)
        end_fill()

        up()
        goto(-225 + 20*n, -315)
        down()
        color('white')
        begin_fill()
        for i in range(4):
            fd(10)
            lt(90)
        end_fill()

        up()
        goto(-225 + 20*n, -295)
        down()
        color('white')
        begin_fill()
        for i in range(4):
            fd(10)
            lt(90)
        end_fill()

        up()
        goto(-225 + 20*n, -275)
        down()
        color('white')
        begin_fill()
        for i in range(4):
            fd(10)
            lt(90)
        end_fill()

        up()
        goto(-225 + 20*n, -255)
        down()
        color('white')
        begin_fill()
        for i in range(4):
            fd(10)
            lt(90)
        end_fill()

        up()
        goto(-225 + 20*n, -235)
        down()
        color('white')
        begin_fill()
        for i in range(4):
            fd(10)
            lt(90)
        end_fill()

        up()
        goto(-225 + 20*n, -215)
        down()
        color('white')
        begin_fill()
        for i in range(4):
            fd(10)
            lt(90)
        end_fill()

        up()
        goto(-225 + 20*n, -195)
        down()
        color('white')
        begin_fill()
        for i in range(4):
            fd(10)
            lt(90)
        end_fill()

        up()
        goto(-225 + 20*n, -175)
        down()
        color('white')
        begin_fill()
        for i in range(4):
            fd(10)
            lt(90)
        end_fill()

        up()
        goto(-225 + 20*n, -155)
        down()
        color('white')
        begin_fill()
        for i in range(4):
            fd(10)
            lt(90)
        end_fill()

        up()
        goto(-225 + 20*n, -135)
        down()
        color('white')
        begin_fill()
        for i in range(4):
            fd(10)
            lt(90)
        end_fill()

        up()
        goto(-225 + 20*n, -115)
        down()
        color('white')
        begin_fill()
        for i in range(4):
            fd(10)
            lt(90)
        end_fill()

        up()
        goto(-225 + 20*n, -95)
        down()
        color('white')
        begin_fill()
        for i in range(4):
            fd(10)
            lt(90)
        end_fill()

        up()
        goto(-225 + 20*n, -75)
        down()
        color('white')
        begin_fill()
        for i in range(4):
            fd(10)
            lt(90)
        end_fill()

        up()
        goto(-225 + 20*n, -55)
        down()
        color('white')
        begin_fill()
        for i in range(4):
            fd(10)
            lt(90)
        end_fill()

    #house 2
    up()
    home()
    down()
    speed(0)
    up()
    goto(-30, -380)
    down()
    color('dark gray')
    begin_fill()
    fd(100)
    lt(90)
    fd(350)
    lt(90)
    fd(100)
    lt(90)
    fd(350)
    end_fill()
    lt(90)
    n = 0
    while n < 5:
        n += 1
        up()
        goto(-45 + 20*n, -375)
        down()
        color('white')
        begin_fill()
        for i in range(4):
            fd(10)
            lt(90)
        end_fill()

        up()
        goto(-45 + 20*n, -355)
        down()
        color('white')
        begin_fill()
        for i in range(4):
            fd(10)
            lt(90)
        end_fill()

        up()
        goto(-45 + 20*n, -335)
        down()
        color('white')
        begin_fill()
        for i in range(4):
            fd(10)
            lt(90)
        end_fill()

        up()
        goto(-45 + 20*n, -315)
        down()
        color('white')
        begin_fill()
        for i in range(4):
            fd(10)
            lt(90)
        end_fill()

        up()
        goto(-45 + 20*n, -295)
        down()
        color('white')
        begin_fill()
        for i in range(4):
            fd(10)
            lt(90)
        end_fill()

        up()
        goto(-45 + 20*n, -275)
        down()
        color('white')
        begin_fill()
        for i in range(4):
            fd(10)
            lt(90)
        end_fill()

        up()
        goto(-45 + 20*n, -255)
        down()
        color('white')
        begin_fill()
        for i in range(4):
            fd(10)
            lt(90)
        end_fill()

        up()
        goto(-45 + 20*n, -235)
        down()
        color('white')
        begin_fill()
        for i in range(4):
            fd(10)
            lt(90)
        end_fill()

        up()
        goto(-45 + 20*n, -215)
        down()
        color('white')
        begin_fill()
        for i in range(4):
            fd(10)
            lt(90)
        end_fill()

        up()
        goto(-45 + 20*n, -195)
        down()
        color('white')
        begin_fill()
        for i in range(4):
            fd(10)
            lt(90)
        end_fill()

        up()
        goto(-45 + 20*n, -175)
        down()
        color('white')
        begin_fill()
        for i in range(4):
            fd(10)
            lt(90)
        end_fill()

        up()
        goto(-45 + 20*n, -155)
        down()
        color('white')
        begin_fill()
        for i in range(4):
            fd(10)
            lt(90)
        end_fill()

        up()
        goto(-45 + 20*n, -135)
        down()
        color('white')
        begin_fill()
        for i in range(4):
            fd(10)
            lt(90)
        end_fill()

        up()
        goto(-45 + 20*n, -115)
        down()
        color('white')
        begin_fill()
        for i in range(4):
            fd(10)
            lt(90)
        end_fill()

        up()
        goto(-45 + 20*n, -95)
        down()
        color('white')
        begin_fill()
        for i in range(4):
            fd(10)
            lt(90)
        end_fill()

        up()
        goto(-45 + 20*n, -75)
        down()
        color('white')
        begin_fill()
        for i in range(4):
            fd(10)
            lt(90)
        end_fill()

        up()
        goto(-45 + 20*n, -55)
        down()
        color('white')
        begin_fill()
        for i in range(4):
            fd(10)
            lt(90)
        end_fill()
    #house 1
    up()
    home()
    down()
    speed(0)
    up()
    goto(-120, -380)
    down()
    color('black')
    begin_fill()
    fd(100)
    lt(90)
    fd(150)
    lt(90)
    fd(100)
    lt(90)
    fd(150)
    end_fill()
    lt(90)
    n = 0
    while n < 5:
        n += 1
        up()
        goto(-135 + 20*n, -375)
        down()
        color('white')
        begin_fill()
        for i in range(4):
            fd(10)
            lt(90)
        end_fill()

        up()
        goto(-135 + 20*n, -355)
        down()
        color('white')
        begin_fill()
        for i in range(4):
            fd(10)
            lt(90)
        end_fill()

        up()
        goto(-135 + 20*n, -335)
        down()
        color('white')
        begin_fill()
        for i in range(4):
            fd(10)
            lt(90)
        end_fill()

        up()
        goto(-135 + 20*n, -315)
        down()
        color('white')
        begin_fill()
        for i in range(4):
            fd(10)
            lt(90)
        end_fill()

        up()
        goto(-135 + 20*n, -295)
        down()
        color('white')
        begin_fill()
        for i in range(4):
            fd(10)
            lt(90)
        end_fill()

        up()
        goto(-135 + 20*n, -275)
        down()
        color('white')
        begin_fill()
        for i in range(4):
            fd(10)
            lt(90)
        end_fill()

        up()
        goto(-135 + 20*n, -255)
        down()
        color('white')
        begin_fill()
        for i in range(4):
            fd(10)
            lt(90)
        end_fill()

    #house 3
    up()
    home()
    down()
    speed(0)
    up()
    goto(100, -380)
    down()
    color('maroon')
    begin_fill()
    fd(100)
    lt(90)
    fd(250)
    lt(90)
    fd(100)
    lt(90)
    fd(150)
    end_fill()
    lt(90)
    n = 0
    while n < 5:
        n += 1
        up()
        goto(85 + 20*n, -375)
        down()
        color('white')
        begin_fill()
        for i in range(4):
            fd(10)
            lt(90)
        end_fill()

        up()
        goto(85 + 20*n, -355)
        down()
        color('white')
        begin_fill()
        for i in range(4):
            fd(10)
            lt(90)
        end_fill()

        up()
        goto(85 + 20*n, -335)
        down()
        color('white')
        begin_fill()
        for i in range(4):
            fd(10)
            lt(90)
        end_fill()

        up()
        goto(85 + 20*n, -315)
        down()
        color('white')
        begin_fill()
        for i in range(4):
            fd(10)
            lt(90)
        end_fill()

        up()
        goto(85 + 20*n, -295)
        down()
        color('white')
        begin_fill()
        for i in range(4):
            fd(10)
            lt(90)
        end_fill()

        up()
        goto(85 + 20*n, -275)
        down()
        color('white')
        begin_fill()
        for i in range(4):
            fd(10)
            lt(90)
        end_fill()

        up()
        goto(85 + 20*n, -255)
        down()
        color('white')
        begin_fill()
        for i in range(4):
            fd(10)
            lt(90)
        end_fill()

        up()
        goto(85 + 20*n, -235)
        down()
        color('white')
        begin_fill()
        for i in range(4):
            fd(10)
            lt(90)
        end_fill()

        up()
        goto(85 + 20*n, -215)
        down()
        color('white')
        begin_fill()
        for i in range(4):
            fd(10)
            lt(90)
        end_fill()

        up()
        goto(85 + 20*n, -195)
        down()
        color('white')
        begin_fill()
        for i in range(4):
            fd(10)
            lt(90)
        end_fill()

        up()
        goto(85 + 20*n, -175)
        down()
        color('white')
        begin_fill()
        for i in range(4):
            fd(10)
            lt(90)
        end_fill()

        up()
        goto(85 + 20*n, -155)
        down()
        color('white')
        begin_fill()
        for i in range(4):
            fd(10)
            lt(90)
        end_fill()
