from turtle import *
#traffic light
def traffic_light():
    up()
    home()
    down()
    up()
    goto(350, -435)
    down()
    color('light steel blue')
    begin_fill()
    fd(5)
    lt(90)
    fd(30)
    lt(90)
    fd(5)
    lt(90)
    fd(30)
    bk(30)
    lt(90)
    end_fill()
    begin_fill()
    bk(8)
    fd(21)
    lt(90)
    fd(35)
    lt(90)
    fd(21)
    lt(90)
    fd(35)
    end_fill()
    up()
    home()
    down()
    up()
    goto(358, -376)
    lt(90)
    begin_fill()
    color('red')
    circle(5)
    position()
    end_fill()
    up()
    goto(357, -387)
    down()
    begin_fill()
    color('yellow')
    circle(4)
    position()
    end_fill()
    up()
    goto(357, -398)
    down()
    begin_fill()
    color('green')
    circle(4)
    position()
    end_fill()
